<link type="text/css" href="{$baseUri}css/ui-lightness/jquery-ui-1.8.14.custom.css" rel="stylesheet">
<script src="{$baseUri}js/jquery-1.5.1.min.js" type="text/javascript"></script>
<script src="{$baseUri}js/jquery-ui-1.8.14.custom.min.js" type="text/javascript"></script>
<script src="{$baseUri}js/jquery.ui.datepicker-cs.js" type="text/javascript"></script>
<script type="text/javascript" src="{$baseUri}js/edataanw.js"></script>


<div class="formulardiv">
    <div class="formularcaption">
        EDATA Anwesenheit / dochazka
    </div>

    <div class="formularbody">
        <div class="formularfieldset" id="mafilter">
            <h1>Auswahlfilter</h1>
            <table>
                <tr>
                    <td>
                        <span title="vyberte datum" class="fieldlabel">{$form['datum']->label}</span>
                    </td>
                    <td>
                        <span title="vyberte datum" class="formularcontrol">{$form['datum']->control}</span>
                    </td>
                    
                    <td>
                        <span title="zadejte Persnr" class="fieldlabel">{$form['persnr']->label}</span>
                    </td>
                    <td>
                        <span title="zadejte Persnr" class="formularcontrol">{$form['persnr']->control}</span>
                    </td>

                </tr>

            </table>
        </div>

    </div>
</div>

<div id="edataanwtable">
{!$edataanwtableContent}
</div>